### ISSUE TITLE
Speed of the software

### ISSUE THREAD

**Issue by PikAsriel** [gameblabla/pokemini#5]
The speed of the game is always over 100% (i.e. 102% - 103%). Is there way to make the software stay in 100% speed

**Comment by gameblabla** [comment]
Which port of Pokemini ? The GCW0/Opendingux one ?
Part of the reason why this could happen is that it entirely relies on triple buffering for blocking and disables waiting. This was done intentionally to get rid of tearing completely, at the possible expense that software might run a bit faster than usual.

**Comment by PikAsriel** [comment]
Seems like all Pokemini have this problem but I have disabled vertical sync. As I sometimes use pokemini as emulator to speedrun, is there any way to make it be 100%?

**Comment by gameblabla** [comment]
> Seems like all Pokemini have this problem but I have disabled vertical sync. As I sometimes use pokemini as emulator to speedrun, is there any way to make it be 100%?

Took a look at my GCW0 port again and realized it did not use triple buffering. This could be fixed by forcing it i suppose. Lemme release a test build and put it later

**Comment by PikAsriel** [comment]
Ok thank you

**Comment by PikAsriel** [comment]
By the way, do you have Discord? I have another question to ask.

**Comment by gameblabla** [comment]
> By the way, do you have Discord? I have another question to ask.

Go on the Retro Game Handhelds discord, i'm always here.
